Repository netobserv/flowlogs-pipeline, pull requests merged in 2023-03, with the labels that each got.

#397 Avoid searching new connections in the multi-ordered-map
  pkg/pipeline/extract/conntrack/store.go
Labels: lgtm

#391 conntrack: handle TCP flags
  README.md
  docs/api.md
  docs/operational-metrics.md
  go.mod
  go.sum
  pkg/api/conntrack.go
  pkg/api/conntrack_test.go
  pkg/config/generic_map.go
  pkg/config/generic_map_test.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/decode/decode_protobuf.go
  pkg/pipeline/decode/decode_protobuf_test.go
  pkg/pipeline/encode/encode_kafka_test.go
  pkg/pipeline/extract/conntrack/aggregator_test.go
  pkg/pipeline/extract/conntrack/conn.go
  pkg/pipeline/extract/conntrack/conn_test.go
  pkg/pipeline/extract/conntrack/conntrack.go
  pkg/pipeline/extract/conntrack/conntrack_test.go
  pkg/pipeline/extract/conntrack/metrics.go
  pkg/pipeline/extract/conntrack/store.go
  pkg/pipeline/extract/conntrack/tcpflags.go
  pkg/pipeline/ingest/ingest_kafka_test.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_builder.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/utils/multiorderedmap.go
  pkg/pipeline/utils/multiorderedmap_test.go
  vendor/github.com/netobserv/gopipes/pkg/internal/refl/channel.go
  vendor/github.com/netobserv/gopipes/pkg/internal/refl/function.go
  vendor/github.com/netobserv/gopipes/pkg/internal/refl/helpers.go
  vendor/github.com/netobserv/gopipes/pkg/node/internal/connect/connectors.go
  vendor/github.com/netobserv/gopipes/pkg/node/node.go
  vendor/github.com/netobserv/gopipes/pkg/node/options.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/flow.pb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/flow_grpc.pb.go
  vendor/modules.txt
Labels: enhancement, lgtm

#399 Move prometheus server to main
  README.md
  cmd/flowlogs-pipeline/main.go
  cmd/flowlogs-pipeline/main_test.go
  docs/api.md
  network_definitions/config.yaml
  pkg/api/encode_prom.go
  pkg/confgen/confgen_test.go
  pkg/confgen/config_test.go
  pkg/confgen/flowlogs2metrics_config.go
  pkg/config/config.go
  pkg/config/pipeline_builder_test.go
  pkg/operational/metrics.go
  pkg/pipeline/aggregate_prom_test.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_test.go
  pkg/pipeline/encode/prom_cache_test.go
  pkg/pipeline/utils/prom_server.go
  pkg/test/network_defs.go
Labels: breaking-change, lgtm, do-not-merge/hold

#402 fix e2e test
  pkg/test/e2e/pipline/flp-config.yaml
Labels: lgtm

#400 Remove unused (?) codecov secret
  .github/workflows/pull_request.yml
Labels: lgtm, approved

#403 Test ConvertToBool
  pkg/utils/convert.go
  pkg/utils/convert_test.go
Labels: lgtm

#410 tcp flags: Update readme and default configuration
  README.md
  contrib/dashboards/jsonnet/dashboard_details.jsonnet
  contrib/dashboards/jsonnet/dashboard_totals.jsonnet
  contrib/kubernetes/flowlogs-pipeline.conf.yaml
  network_definitions/config.yaml
Labels: lgtm

#404 NETOBSERV-924 adapt to new ovn annotation format
  pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes.go
  pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes_test.go
Labels: ok-to-test, qe-approved, lgtm, approved

#411 make expiryTime in encode_prom into a Duration
  docs/api.md
  pkg/api/encode_prom.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/aggregate_prom_test.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_test.go
Labels: breaking-change, lgtm, approved

#415 conntrack: Fix a bug in swapAB
  pkg/pipeline/extract/conntrack/conn.go
  pkg/pipeline/extract/conntrack/conntrack.go
  pkg/pipeline/extract/conntrack/conntrack_test.go
Labels: ok-to-test, lgtm, approved
