Repository netobserv/flowlogs-pipeline, pull requests merged in 2023-05, with the labels that each got.

#431 Remove error logs in processing loop
  pkg/pipeline/ingest/ingest_grpc.go
  pkg/pipeline/ingest/ingest_kafka.go
Labels: lgtm, approved

#418 shorten default timeout for aggregate; allow configuration of timeout for aggregates
  docs/api.md
  network_definitions/bandwidth_per_network_service.yaml
  network_definitions/bandwidth_per_src_dest_subnet.yaml
  network_definitions/bandwidth_per_src_subnet.yaml
  network_definitions/connection_length_histogram.yaml
  network_definitions/connection_rate_per_dest_subnet.yaml
  network_definitions/connection_rate_per_src_subnet.yaml
  network_definitions/connection_rate_per_tcp_flags.yaml
  network_definitions/connections_per_dst_as.yaml
  network_definitions/connections_per_src_as.yaml
  network_definitions/count_per_src_dest_subnet.yaml
  network_definitions/egress_bandwidth_per_dest_subnet.yaml
  network_definitions/egress_bandwidth_per_namespace.yaml
  network_definitions/flows_length_histogram.yaml
  network_definitions/geo-location_rate_per_dest.yaml
  network_definitions/network_services_count.yaml
  pkg/api/api.go
  pkg/api/extract_aggregate.go
  pkg/confgen/confgen.go
  pkg/confgen/confgen_test.go
  pkg/confgen/dedup.go
  pkg/confgen/dedup_test.go
  pkg/confgen/doc.go
  pkg/confgen/extract.go
  pkg/confgen/flowlogs2metrics_config.go
  pkg/config/config.go
  pkg/config/pipeline_builder.go
  pkg/config/pipeline_builder_test.go
  pkg/config/stage_params.go
  pkg/pipeline/aggregate_prom_test.go
  pkg/pipeline/extract/aggregate/aggregates.go
  pkg/pipeline/extract/aggregate/aggregates_test.go
  pkg/pipeline/extract/extract_aggregate.go
  pkg/pipeline/extract/extract_aggregate_test.go
  pkg/test/e2e/pipline/flp-config.yaml
  pkg/test/network_defs.go
Labels: ok-to-test, breaking-change, lgtm

#435 fix manifset build
  Makefile
Labels: ok-to-test, lgtm, approved

#438 Update workflow, setup workflow-test
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .mk/shortcuts.mk
  Makefile
  contrib/docker/shortlived.Dockerfile
Labels: lgtm, approved

#424 NETOBSERV-974 Implement SASL for Kafka (producer+consumer)
  go.mod
  pkg/api/encode_kafka.go
  pkg/api/enum.go
  pkg/api/ingest_kafka.go
  pkg/api/sasl.go
  pkg/api/tls.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/encode/encode_kafka.go
  pkg/pipeline/ingest/ingest_kafka.go
  pkg/pipeline/utils/sasl.go
  vendor/github.com/segmentio/kafka-go/sasl/plain/plain.go
  vendor/github.com/segmentio/kafka-go/sasl/scram/scram.go
  vendor/github.com/xdg/scram/.gitignore
  vendor/github.com/xdg/scram/.travis.yml
  vendor/github.com/xdg/scram/LICENSE
  vendor/github.com/xdg/scram/README.md
  vendor/github.com/xdg/scram/client.go
  vendor/github.com/xdg/scram/client_conv.go
  vendor/github.com/xdg/scram/common.go
  vendor/github.com/xdg/scram/doc.go
  vendor/github.com/xdg/scram/parse.go
  vendor/github.com/xdg/scram/scram.go
  vendor/github.com/xdg/scram/server.go
  vendor/github.com/xdg/scram/server_conv.go
  vendor/github.com/xdg/stringprep/.gitignore
  vendor/github.com/xdg/stringprep/.travis.yml
  vendor/github.com/xdg/stringprep/LICENSE
  vendor/github.com/xdg/stringprep/README.md
  vendor/github.com/xdg/stringprep/bidi.go
  vendor/github.com/xdg/stringprep/doc.go
  vendor/github.com/xdg/stringprep/error.go
  vendor/github.com/xdg/stringprep/map.go
  vendor/github.com/xdg/stringprep/profile.go
  vendor/github.com/xdg/stringprep/saslprep.go
  vendor/github.com/xdg/stringprep/set.go
  vendor/github.com/xdg/stringprep/tables.go
  vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
  vendor/modules.txt
Labels: no-qe, no-doc, lgtm, approved

#427 Fix naming of k8s entries to ipfix export
  hack/examples/ipfix-collector/ipfix-dump.go
  pkg/pipeline/write/write_ipfix.go
Labels: lgtm, approved
