Repository netobserv/flowlogs-pipeline, pull requests merged in 2023-11, with the labels that each got.

#534 Move Mountain View 2 kilometers south
  pkg/pipeline/transform/transform_network_test.go
Labels: no-qe, no-doc, lgtm, approved

#474 NETOBSERV-1247: using Meta informer for replicaSets
  pkg/pipeline/transform/kubernetes/kubernetes.go
  vendor/k8s.io/client-go/metadata/metadatainformer/informer.go
  vendor/k8s.io/client-go/metadata/metadatainformer/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/lister.go
  vendor/k8s.io/client-go/metadata/metadatalister/shim.go
  vendor/modules.txt
Labels: ok-to-test, qe-approved, lgtm, approved, jira/valid-reference

#513 NETOBSERV-1231: Improve promencode API: scaling & filters
  docs/api.md
  pkg/api/api.go
  pkg/api/encode_prom.go
  pkg/api/enum.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_metric.go
  pkg/pipeline/encode/encode_prom_test.go
Labels: ok-to-test, breaking-change, no-qe, no-doc, jira/valid-reference

#532 Allow multiple prometheus stages with different URLs
  cmd/flowlogs-pipeline/main.go
  pkg/api/encode_prom.go
  pkg/confgen/flowlogs2metrics_config.go
  pkg/config/config.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_test.go
  pkg/pipeline/utils/prom_server.go
Labels: ok-to-test, lgtm

#537 Fix crash when metrics settings are unset
  pkg/confgen/flowlogs2metrics_config.go
  pkg/config/config.go
Labels: no-qe, no-doc, lgtm

#538 Allow to start FLP directly from the flow logs producer
  cmd/flowlogs-pipeline/main.go
  pkg/confgen/flowlogs2metrics_config.go
  pkg/config/config.go
  pkg/config/pipeline_builder.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/ingest/ingest_inprocess.go
  pkg/pipeline/inprocess.go
  pkg/pipeline/inprocess_test.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_builder.go
  pkg/pipeline/utils/prom_server.go
  pkg/prometheus/prom_server.go
Labels: no-qe, no-doc, lgtm, approved
