Repository netobserv/flowlogs-pipeline, pull requests merged in 2023-09, with the labels that each got.

#453 move add_if and add_regex_if to transform_filter from transform_network
  README.md
  docs/api.md
  pkg/api/transform_filter.go
  pkg/api/transform_network.go
  pkg/pipeline/transform/transform_filter.go
  pkg/pipeline/transform/transform_filter_test.go
  pkg/pipeline/transform/transform_network.go
  pkg/pipeline/transform/transform_network_test.go
Labels: ok-to-test, breaking-change, no-qe, no-doc, lgtm, approved

#447 initial support for labels
  docs/api.md
  go.sum
  pkg/api/transform_filter.go
  pkg/pipeline/transform/transform_filter.go
  pkg/pipeline/transform/transform_filter_test.go
Labels: lgtm

#490 NETOBSERV-1222: create PR template
  .github/pull_request_template.md
Labels: lgtm, approved, jira/valid-reference

#491 Fixes a couple of minor weaknesses
  cmd/flowlogs-pipeline/main.go
  pkg/pipeline/encode/encode_kafka.go
  pkg/pipeline/extract/aggregate/aggregate.go
  pkg/pipeline/extract/aggregate/aggregate_test.go
  pkg/pipeline/extract/timebased/filters.go
  pkg/pipeline/ingest/ingest_kafka.go
  pkg/pipeline/ingest/ingest_synthetic.go
  pkg/pipeline/write/write_ipfix.go
Labels: no-qe, no-doc, lgtm, approved
