Repository netobserv/flowlogs-pipeline, pull requests merged in 2023-04, with the labels that each got.

#414 NETOBSERV-962 - ADD write ipfix stage to pipeline builder
  pkg/config/pipeline_builder.go
  pkg/config/pipeline_builder_test.go
  pkg/config/stage_params.go
Labels: lgtm, approved

#422 [Backport] Conntrack output field copy operations + fix duplicates
  README.md
  contrib/kubernetes/flowlogs-pipeline.conf.yaml
  docs/api.md
  docs/operational-metrics.md
  network_definitions/config.yaml
  pkg/api/conntrack.go
  pkg/pipeline/conntrack_integ_test.go
  pkg/pipeline/extract/conntrack/aggregator.go
  pkg/pipeline/extract/conntrack/aggregator_test.go
  pkg/pipeline/extract/conntrack/conn.go
  pkg/pipeline/extract/conntrack/conntrack.go
  pkg/pipeline/extract/conntrack/conntrack_test.go
  pkg/pipeline/extract/conntrack/hash_test.go
  pkg/pipeline/extract/conntrack/metrics.go
  pkg/pipeline/extract/conntrack/store.go
  pkg/pipeline/extract/conntrack/utils_test.go
Labels: ok-to-test, lgtm, approved

#413 Conntrack output field copy operations + fix duplicates
  README.md
  contrib/kubernetes/flowlogs-pipeline.conf.yaml
  docs/api.md
  docs/operational-metrics.md
  network_definitions/config.yaml
  pkg/api/conntrack.go
  pkg/pipeline/conntrack_integ_test.go
  pkg/pipeline/extract/conntrack/aggregator.go
  pkg/pipeline/extract/conntrack/aggregator_test.go
  pkg/pipeline/extract/conntrack/conn.go
  pkg/pipeline/extract/conntrack/conntrack.go
  pkg/pipeline/extract/conntrack/conntrack_test.go
  pkg/pipeline/extract/conntrack/hash_test.go
  pkg/pipeline/extract/conntrack/metrics.go
  pkg/pipeline/extract/conntrack/store.go
  pkg/pipeline/extract/conntrack/utils_test.go
Labels: lgtm, approved

#416 conntrack: Add operational metrics on errors for hash computation and aggregators
  docs/operational-metrics.md
  pkg/pipeline/extract/conntrack/aggregator.go
  pkg/pipeline/extract/conntrack/aggregator_test.go
  pkg/pipeline/extract/conntrack/conntrack.go
  pkg/pipeline/extract/conntrack/conntrack_test.go
  pkg/pipeline/extract/conntrack/hash.go
  pkg/pipeline/extract/conntrack/hash_test.go
  pkg/pipeline/extract/conntrack/metrics.go
  pkg/pipeline/extract/conntrack/store.go
  pkg/test/utils.go
Labels: lgtm, approved

#408 NETOBSERV-934: Add icmpv4/v6 bits to FLP
  go.mod
  go.sum
  pkg/pipeline/decode/decode_protobuf.go
  pkg/pipeline/decode/decode_protobuf_test.go
  pkg/pipeline/pipeline_test.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/grpc/client.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/flow.pb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/flow_grpc.pb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/utils/utils.go
  vendor/modules.txt
Labels: ok-to-test, qe-approved, lgtm, approved, jira/valid-reference

#428 NETOBSERV-984 - KafkaInterBrokerProtocalVersion throws warning and has ingestion errors
  pkg/pipeline/decode/decode_protobuf.go
  pkg/pipeline/ingest/ingest_grpc.go
  pkg/pipeline/ingest/ingest_kafka.go
Labels: ok-to-test, qe-approved, lgtm, approved
