Repository netobserv/flowlogs-pipeline, pull requests merged in 2024-11, with the labels that each got.

#733 backport NETOBSERV-1633 Konflux prefetch
  .tekton/flowlogs-pipeline-pull-request.yaml
  .tekton/flowlogs-pipeline-push.yaml
  .tekton/pipeline-ref.yaml
  contrib/docker/Dockerfile.downstream
  hack/update-build.sh
Labels: lgtm, approved

#748 Bumped golangci-lint from v1.56.2 to v1.61.0
  .golangci.yml
  Makefile
  README.md
  cmd/apitodoc/main.go
  docs/operational-metrics.md
  pkg/api/encode_s3.go
  pkg/confgen/confgen.go
  pkg/confgen/doc.go
  pkg/confgen/grafana_jsonnet.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_metric.go
  pkg/pipeline/encode/metrics_common.go
  pkg/pipeline/encode/opentelemetry/opentelemetry.go
  pkg/pipeline/extract/aggregate/aggregate.go
  pkg/pipeline/extract/aggregate/aggregates.go
  pkg/pipeline/extract/conntrack/conntrack_test.go
  pkg/pipeline/extract/timebased/filters.go
  pkg/pipeline/extract/timebased/timebased.go
  pkg/pipeline/transform/kubernetes/enrich.go
  pkg/pipeline/transform/location/location_test.go
  pkg/pipeline/transform/transform_generic.go
  pkg/pipeline/write/grpc/grpc_test.go
  pkg/pipeline/write/testnorace/write_ipfix_test.go
  pkg/pipeline/write/write_ipfix.go
  pkg/pipeline/write/write_loki.go
  pkg/test/e2e/utils.go
  pkg/test/utils.go
Labels: lgtm, approved, needs-ok-to-test

#756 Fix nudges configuration in konflux
  .tekton/flowlogs-pipeline-1-7-push.yaml
Labels: lgtm, approved

#757 Added new rpms-check image
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#739 NETOBSERV-1935: enable metrics from list/nested fields
  docs/api.md
  pkg/api/encode_prom.go
  pkg/confgen/confgen_test.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_test.go
  pkg/pipeline/encode/metrics/filtering.go
  pkg/pipeline/encode/metrics/flattening.go
  pkg/pipeline/encode/metrics/preprocess.go
  pkg/pipeline/encode/metrics/preprocess_test.go
  pkg/pipeline/encode/metrics_common.go
  pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go
  pkg/pipeline/extract/aggregate/aggregate.go
  pkg/pipeline/ingest/ingest_grpc.go
  pkg/pipeline/write/write_loki.go
Labels: jira/valid-reference

#761 KONFLUX Fix source build tagging
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#762 Fix konflux results
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#763 Fixing version in downstream builds
  .tekton/pipeline-ref.yaml
  contrib/docker/Dockerfile.downstream
Labels: lgtm, approved

#740 NETOBSERV-1692: allow KEEP filtering logic
  docs/api.md
  pkg/api/transform_filter.go
  pkg/pipeline/encode/metrics/preprocess.go
  pkg/pipeline/encode/metrics/preprocess_test.go
  pkg/pipeline/transform/transform_filter.go
  pkg/pipeline/transform/transform_filter_test.go
  pkg/utils/convert.go
  pkg/utils/filters/filters.go
  pkg/utils/filters/filters_test.go
Labels: lgtm, jira/valid-reference

#747 NETOBSERV-1890: decode TCP flags (new stage/rule)
  docs/api.md
  pkg/api/transform_network.go
  pkg/pipeline/transform/transform_network.go
  pkg/utils/tcp_flags.go
  pkg/utils/tcp_flags_test.go
Labels: ok-to-test, qe-approved, lgtm, jira/valid-reference

#765 Fix version in konflux build
  .tekton/pipeline-ref.yaml
  contrib/docker/Dockerfile.downstream
Labels: lgtm, approved
