Repository netobserv/flowlogs-pipeline, pull requests merged in 2024-03, with the labels that each got.

#623 Add test covering use of viper with unmarshaller
  pkg/config/config_test.go
Labels: lgtm, approved

#601 NETOBSERV-1466 Update eBPF dependency for FLP
  go.mod
  go.sum
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/write/testnorace/write_ipfix_test.go
  pkg/pipeline/write/write_ipfix.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/decode/decode_protobuf.go
  vendor/modules.txt
Labels: breaking-change, lgtm, approved

#621 NETOBSERV-1471 add gRPC write stage
  pkg/api/write_grpc.go
  pkg/config/config.go
  pkg/pipeline/pipeline_builder.go
  pkg/pipeline/write/grpc/client.go
  pkg/pipeline/write/grpc/genericmap/genericmap.pb.go
  pkg/pipeline/write/grpc/genericmap/genericmap_grpc.pb.go
  pkg/pipeline/write/grpc/grpc_test.go
  pkg/pipeline/write/grpc/server.go
  pkg/pipeline/write/write_grpc.go
  pkg/pipeline/write/write_grpc_test.go
  proto/README.md
  proto/genericmap.proto
Labels: lgtm, approved

#633 Provide k8s templates to just deploy an ipfix collector
  contrib/kubernetes/ipfix-collector-stdout.yaml
Labels: lgtm, approved

#630 NETOBSERV-1566: ipfix: make RTT optional
  pkg/pipeline/write/testnorace/write_ipfix_test.go
  pkg/pipeline/write/write_ipfix.go
Labels: qe-approved, approved, jira/valid-reference

#635 update examples, minor changes
  README.md
  contrib/kubernetes/flowlogs-pipeline.conf.yaml
  network_definitions/bandwidth_per_network_service.yaml
  network_definitions/bandwidth_per_src_dest_subnet.yaml
  network_definitions/bandwidth_per_src_subnet.yaml
  network_definitions/connection_rate_per_dest_subnet.yaml
  network_definitions/connection_rate_per_src_subnet.yaml
  network_definitions/count_per_src_dest_subnet.yaml
  network_definitions/egress_bandwidth_per_dest_subnet.yaml
  network_definitions/egress_bandwidth_per_namespace.yaml
  network_definitions/flows_length_histogram.yaml
  network_definitions/geo-location_rate_per_dest.yaml
  network_definitions/network_services_count.yaml
  pkg/api/api.go
  pkg/api/encode_prom.go
  pkg/confgen/confgen.go
  pkg/confgen/transform.go
  pkg/config/pipeline_builder_test.go
Labels: no-qe, no-doc, lgtm, approved

#614 Enum replacement in API
  Makefile
  README.md
  cmd/apitodoc/main.go
  docs/api.md
  hack/update-enum-docs.sh
  pkg/api/api.go
  pkg/api/conntrack.go
  pkg/api/conntrack_test.go
  pkg/api/decoder.go
  pkg/api/encode_kafka.go
  pkg/api/encode_prom.go
  pkg/api/enum.go
  pkg/api/extract_timebased.go
  pkg/api/sasl.go
  pkg/api/transform_filter.go
  pkg/api/transform_generic.go
  pkg/api/transform_network.go
  pkg/confgen/confgen_test.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/conntrack_integ_test.go
  pkg/pipeline/decode/decode.go
  pkg/pipeline/encode/encode_kafka.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_metric.go
  pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go
  pkg/pipeline/extract/conntrack/aggregator.go
  pkg/pipeline/extract/conntrack/conntrack.go
  pkg/pipeline/extract/conntrack/conntrack_test.go
  pkg/pipeline/extract/conntrack/utils_test.go
  pkg/pipeline/extract/extract_timebased_test.go
  pkg/pipeline/extract/timebased/filters.go
  pkg/pipeline/extract/timebased/timebased.go
  pkg/pipeline/ingest/ingest_kafka.go
  pkg/pipeline/ingest/ingest_stdin.go
  pkg/pipeline/transform/kubernetes/enrich_test.go
  pkg/pipeline/transform/transform_filter.go
  pkg/pipeline/transform/transform_filter_test.go
  pkg/pipeline/transform/transform_generic.go
  pkg/pipeline/transform/transform_network.go
  pkg/pipeline/transform/transform_network_direction.go
  pkg/pipeline/transform/transform_network_test.go
  pkg/pipeline/utils/sasl.go
Labels: ok-to-test, no-qe, no-doc, lgtm, approved

#642 NETOBSERV-1471 update eBPF dep
  go.mod
  go.sum
  pkg/pipeline/ingest/ingest_grpc.go
  pkg/pipeline/pipeline_test.go
  vendor/github.com/cilium/ebpf/Makefile
  vendor/github.com/cilium/ebpf/btf/btf.go
  vendor/github.com/cilium/ebpf/btf/core.go
  vendor/github.com/cilium/ebpf/btf/marshal.go
  vendor/github.com/cilium/ebpf/btf/strings.go
  vendor/github.com/cilium/ebpf/btf/types.go
  vendor/github.com/cilium/ebpf/cpu.go
  vendor/github.com/cilium/ebpf/internal/auxv.go
  vendor/github.com/cilium/ebpf/internal/kconfig/kconfig.go
  vendor/github.com/cilium/ebpf/internal/memoize.go
  vendor/github.com/cilium/ebpf/internal/sys/types.go
  vendor/github.com/cilium/ebpf/internal/sysenc/marshal.go
  vendor/github.com/cilium/ebpf/internal/tracefs/kprobe.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/internal/vdso.go
  vendor/github.com/cilium/ebpf/internal/version.go
  vendor/github.com/cilium/ebpf/link/link.go
  vendor/github.com/cilium/ebpf/link/netfilter.go
  vendor/github.com/cilium/ebpf/link/syscalls.go
  vendor/github.com/cilium/ebpf/link/uprobe.go
  vendor/github.com/cilium/ebpf/link/uprobe_multi.go
  vendor/github.com/cilium/ebpf/linker.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/marshalers.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/github.com/cilium/ebpf/run-tests.sh
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/grpc/flow/client.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/grpc/flow/server.go
  vendor/golang.org/x/exp/maps/maps.go
  vendor/modules.txt
Labels: lgtm, approved

#586 NETOBSERV-1426: subnet labelling enhancements
  docs/api.md
  pkg/api/transform_network.go
  pkg/pipeline/transform/transform_network.go
  pkg/pipeline/transform/transform_network_test.go
Labels: breaking-change, no-qe, no-doc, lgtm, approved, jira/valid-reference

#644 Add go mod vendor check in CI
  .github/workflows/pull_request.yml
  go.mod
Labels: lgtm, approved
