Repository netobserv/flowlogs-pipeline, pull requests merged in 2024-06, with the labels that each got.

#672 NETOBSERV-1522 Add otel to pipeline builder
  README.md
  pkg/config/pipeline_builder.go
  pkg/config/stage_params.go
Labels: lgtm, approved

#675 NETOBSERV-1707: move to go 1.22
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_e2e.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  contrib/docker/Dockerfile
Labels: no-qe, no-doc, lgtm, approved, jira/valid-reference

#680 Add .ci-operator.yaml
  .ci-operator.yaml
Labels: lgtm

#640 Add new filters allowing FLP-based dedup
  README.md
  docs/api.md
  pkg/api/transform_filter.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/transform/transform_filter.go
  pkg/pipeline/transform/transform_filter_test.go
Labels: breaking-change, no-qe, lgtm, approved
