Repository netobserv/flowlogs-pipeline, pull requests merged in 2024-09, with the labels that each got.

#674 NETOBSERV-1790: Manage enrichment via "k8s.v1.cni.cncf.io/network-status"
  README.md
  docs/api.md
  pkg/api/transform_network.go
  pkg/config/generic_map.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/transform/kubernetes/cni/cni.go
  pkg/pipeline/transform/kubernetes/cni/multus.go
  pkg/pipeline/transform/kubernetes/cni/multus_test.go
  pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes.go
  pkg/pipeline/transform/kubernetes/enrich.go
  pkg/pipeline/transform/kubernetes/enrich_test.go
  pkg/pipeline/transform/kubernetes/informers/informers-mock.go
  pkg/pipeline/transform/kubernetes/informers/informers.go
  pkg/pipeline/transform/kubernetes/informers/informers_test.go
  pkg/pipeline/transform/transform_network.go
Labels: ok-to-test, breaking-change, qe-approved, lgtm, approved, jira/valid-reference

#705 e2e: Relax error checking in logs
  pkg/test/e2e/kafka/kafka_test.go
Labels: no-qe, no-doc, lgtm, approved

#697 NETOBSERV-1792: Added update-build script to add downstream labels
  .tekton/flowlogs-pipeline-pull-request.yaml
  .tekton/flowlogs-pipeline-push.yaml
  hack/update-build.sh
Labels: lgtm, approved, jira/valid-reference

#698 NETOBSERV-1772: allow prom label remapping
  docs/api.md
  pkg/api/encode_prom.go
  pkg/confgen/confgen_test.go
  pkg/config/pipeline_builder_test.go
  pkg/pipeline/encode/encode_prom.go
  pkg/pipeline/encode/encode_prom_metric.go
  pkg/pipeline/encode/encode_prom_test.go
  pkg/pipeline/encode/metrics_common.go
  pkg/pipeline/encode/opentelemetry/encode_otlpmetrics.go
Labels: lgtm, approved, jira/valid-reference

#719 Addressing konflux error and fixing multi arch build with podman 5.2
  .tekton/flowlogs-pipeline-pull-request.yaml
  .tekton/flowlogs-pipeline-push.yaml
  Makefile
  contrib/docker/Dockerfile
  hack/update-build.sh
Labels: lgtm, approved

#711 NETOBSERV-1875: Make enrichment indexes configurable
  README.md
  cmd/flowlogs-pipeline/main_test.go
  contrib/kubernetes/flowlogs-pipeline.conf.yaml
  docs/api.md
  docs/operational-metrics.md
  pkg/api/transform_network.go
  pkg/confgen/dedup_test.go
  pkg/config/pipeline_builder_test.go
  pkg/operational/metrics.go
  pkg/pipeline/pipeline_builder.go
  pkg/pipeline/transform/kubernetes/cni/cni.go
  pkg/pipeline/transform/kubernetes/cni/multus.go
  pkg/pipeline/transform/kubernetes/cni/multus_test.go
  pkg/pipeline/transform/kubernetes/cni/ovn_kubernetes.go
  pkg/pipeline/transform/kubernetes/enrich.go
  pkg/pipeline/transform/kubernetes/enrich_test.go
  pkg/pipeline/transform/kubernetes/informers/informers-mock.go
  pkg/pipeline/transform/kubernetes/informers/informers.go
  pkg/pipeline/transform/kubernetes/informers/informers_test.go
  pkg/pipeline/transform/transform_network.go
  pkg/pipeline/transform/transform_network_test.go
  pkg/test/e2e/pipline/flp-config.yaml
Labels: ok-to-test, breaking-change, qe-approved, lgtm, jira/valid-reference

#722 NETOBSERV-1633 : Add description label to downstream container image
  hack/update-build.sh
Labels: lgtm, approved
