Repository netobserv/flowlogs-pipeline, pull requests merged in 2024-01, with the labels that each got.

#546 NETOBSERV-1298: update netobserv agent package to pick duplist changes
  go.mod
  go.sum
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/decode/decode_protobuf.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/flow.pb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/utils/utils.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#554 NETOBSERV-1244: Add Kubernetes Infra transform rule
  docs/api.md
  pkg/api/api.go
  pkg/api/transform_network.go
  pkg/pipeline/transform/transform_network.go
Labels: lgtm, approved, jira/valid-reference

#575 NETOBSERV-1203: Added option to add zones in k8s transform rule
  pkg/api/transform_network.go
  pkg/pipeline/transform/kubernetes/kubernetes.go
  pkg/pipeline/transform/transform_network.go
  pkg/pipeline/transform/transform_network_test.go
Labels: no-qe, lgtm, approved, jira/valid-reference

#576 NETOBSERV-1308: fix minor vulnerabilities with location db
  pkg/pipeline/transform/location/location.go
  pkg/pipeline/transform/location/location_test.go
Labels: lgtm, jira/valid-reference
