Repository netobserv/flowlogs-pipeline, pull requests merged in 2025-01, with the labels that each got.

#791 update flp to latest agent changes and fix ut
  go.mod
  go.sum
  pkg/pipeline/pipeline_test.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/decode/decode_protobuf.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_arm64_bpfel.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_arm64_bpfel.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_powerpc_bpfel.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_powerpc_bpfel.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_s390_bpfeb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_s390_bpfeb.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_x86_bpfel.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_x86_bpfel.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/gen.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/model/flow_content.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/model/record.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/proto.go
  vendor/modules.txt
Labels: lgtm, approved

#792 NETOBSERV-2055: Update ebpf agent pkgs after removing xlat icmp
  go.mod
  go.sum
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/decode/decode_protobuf.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_arm64_bpfel.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_arm64_bpfel.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_powerpc_bpfel.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_powerpc_bpfel.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_s390_bpfeb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_s390_bpfeb.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_x86_bpfel.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/ebpf/bpf_x86_bpfel.o
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/flow.pb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/proto.go
  vendor/modules.txt
Labels: qe-approved, lgtm, approved, jira/valid-reference

#781 NETOBSERV-1965: udn mapping agent pkg update
  go.mod
  go.sum
  pkg/pipeline/pipeline_test.go
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/compress.go
  vendor/github.com/emicklei/go-restful/v3/curly.go
  vendor/github.com/emicklei/go-restful/v3/entity_accessors.go
  vendor/github.com/emicklei/go-restful/v3/json.go
  vendor/github.com/emicklei/go-restful/v3/jsoniter.go
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/README.md
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/decode/decode_protobuf.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/model/record.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/flow.pb.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/proto.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/observability-lib/ovsdb/interface.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/observability-lib/ovsdb/observ_model.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/observability-lib/sampledecoder/db_client.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/observability-lib/sampledecoder/sample_decoder.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/config/config.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdb/ops/db_object_types.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdb/ops/model.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdb/ops/router.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdb/ops/switch.go
  vendor/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/types/const.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#797 NETOBSERV-1904: Enrich using UDN info
  docs/api.md
  pkg/api/transform_network.go
  pkg/pipeline/transform/kubernetes/cni/multus.go
  pkg/pipeline/transform/kubernetes/cni/udn.go
  pkg/pipeline/transform/kubernetes/cni/udn_test.go
  pkg/pipeline/transform/kubernetes/enrich_test.go
  pkg/pipeline/transform/kubernetes/informers/informers-mock.go
  pkg/pipeline/transform/kubernetes/informers/informers.go
Labels: lgtm, jira/valid-reference

#803 Adding nudge configuration to 1.8 branch
  .tekton/flowlogs-pipeline-1-8-push.yaml
Labels: lgtm, approved

#804 NETOBSERV-2084: get nested data as native maps [backport 1.8]
  go.mod
  go.sum
  pkg/pipeline/encode/encode_prom_test.go
  pkg/pipeline/encode/metrics/flattening.go
  pkg/pipeline/encode/metrics/preprocess_test.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/proto.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference

#802 NETOBSERV-2084: get nested data as native maps
  go.mod
  go.sum
  pkg/pipeline/encode/encode_prom_test.go
  pkg/pipeline/encode/metrics/flattening.go
  pkg/pipeline/encode/metrics/preprocess_test.go
  vendor/github.com/netobserv/netobserv-ebpf-agent/pkg/pbflow/proto.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference
